### ISSUE TITLE
GSSOC'20 contribution making a landing page for ambsql

### ISSUE THREAD

**Issue by eaglewarrior** [ambujraj/AmbSQL#18]

**Comment by Aju100** [comment]
@eaglewarrior  can u assign this i would love to work

**Comment by eaglewarrior** [comment]
Hey @Aju100  let me make the first version and commit you can improve it more

**Comment by Aju100** [comment]
okay

**Comment by eaglewarrior** [comment]
Hey @ambujraj  I have created pull request  #21, I have committed the HTML file and hosted URL link

**Comment by shreyakapoor08** [comment]
can i work on this?

**Comment by eaglewarrior** [comment]
@ambujraj  I have already raised the PR and merged Please I request you to assign me relevant points and close this issue .Thanks

**Comment by eaglewarrior** [comment]
Thanks @ambujraj  for updating my name in credits but yet I have not got any points for it please help me

**Comment by eaglewarrior** [comment]
Thanks @ambujraj  for assigning labels my scores are updated.

Closing this issue and PR #21 is closed
