### ISSUE TITLE
Bug: Table exists NOT CHECKED

### ISSUE THREAD

**Issue by aayanksinghai** [ambujraj/AmbSQL#23]
The Line 184 is always skipped/missed if the table do not exists in the database. 
Moreover, it prints the Line 178, Line 179 (basic design layout) irrespective of the existence of table.
Therefore producing the undesired output.

I would like to work on this.
![tbl](https://user-images.githubusercontent.com/25720367/76168365-44c4f000-6195-11ea-9400-c947170e3eca.JPG)

**Comment by ambujraj** [comment]
Assigned

**Comment by aayanksinghai** [comment]
Thank you, I'll start working on it.

**Comment by aayanksinghai** [comment]
@ambujraj I've raised a PR #26, Please review it.
