### ISSUE TITLE
Add github actions for the project.

### ISSUE THREAD

**Issue by aashimgarg** [ambujraj/AmbSQL#54]
I will add github actions to the project. GitHub Actions makes it easy to automate all your software workflows, now with world-class CI/CD.

Should i work with this as this will be very good for the project.

**Comment by aashimgarg** [comment]
@ambujraj have a look at it as this will be very useful.

**Comment by feni-katharotiya** [comment]
I want to work on this issues with the help of my knowledge please assign me this project ...

**Comment by feni-katharotiya** [comment]
@ambujraj. Hello, I am gssoc participant and would like to work on this issue.

**Comment by ambujraj** [comment]
Go on @feni-katharotiya
