### ISSUE TITLE
PR template

### ISSUE THREAD

**Issue by kichloo** [ambujraj/AmbSQL#57]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
PR template

**Describe alternatives you've considered**

**Additional context**

**Comment by kichloo** [comment]
I can design the PR template for the project.

**Comment by ambujraj** [comment]
sure

**Comment by kichloo** [comment]
@ambujraj Can I create and take the Issue template also? I will complete both in 3 days.

**Comment by ambujraj** [comment]
@kichloo but the issue template is already there!!

**Comment by ambujraj** [comment]
but you want to improve it then you can.

**Comment by kichloo** [comment]
@ambujraj The issue template which I designed have both the bug and the feature request in the same form, thereby, all in one which will be easy and convenient for the user. Do tell me if you want to make a PR.

**Comment by kichloo** [comment]
@ambujraj There can be Easy/Medium label as there is no label right now
